version: "3.8"

volumes:
  db-data:

services:
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_RANDOM_ROOT_PASSWORD=no
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  app:
    build:
      context: ./images/app
    volumes:
      - ./conf/app/php.smtp.ini:/usr/local/etc/php/conf.d/php_smtp.ini
      - ./conf/app/msmtp.msmtprc:/etc/msmtprc
      - ./src:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASS}
    depends_on:
      - db

  web:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./conf/web/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/web/nginx.default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - app

  smtp:
    image: jeanberu/mailcatcher:latest
    ports:
      - "1080:1080"
      - "1025:1025"
